# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf


# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# nwg-displays support
# source=workspaces.conf
# source=monitors.conf

# Shell overrides
source=hyprland/shellOverrides/main.conf

decoration {
    active_opacity = 0.9
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 8
        passes = 2
    }
}